version: '3'
services:

  redis:
    container_name: redis
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis-net
    ports:
      - "6379:6379"

networks:
    redis-net:
